### ISSUE TITLE
The customDateProps event does not give me access to "this" object calendar

### ISSUE THREAD

**Issue by josegerar** [wrick17/calendar-plugin#11]
The customDateProps event does not give me access to "this", from the calendar, the "this" that comes out is window

**Comment by wrick17** [comment]
The `customDateProps` is not an event. It is used to pass custom `classes` and `data attributes` to the element that renders the date.

Consider the example below:
```
customDateProps: (date) => ({
  classes: 'date-element date-element-custom',
  data: {
    type: 'date',
    form: 'date-object'
  }
}),
```
That will translate to the following DOM element where you'll notice the custom classes and the data attributes were added:
![image](https://user-images.githubusercontent.com/8253932/197828522-e2cb50ec-6a02-4e79-b5ec-6b4fbcf87b62.png)

Not an issue.
