### ISSUE TITLE
Uncaught TypeError: $(...).updateCalendarOptions is not a function

### ISSUE THREAD

**Issue by recepgums** [wrick17/calendar-plugin#12]
var options = {
            date: new Date().toJSON().slice(0,10).replace(/-/g,'/'),
            weekDayLength: 1,
            prevButton: 'Onceki',
            nextButton: 'Sonraki',
            monthYearSeparator: ' ',
            onClickToday: function (date) {
                alert('sd')
            },
            onClickMonthPrev: function (date) {
                return false
            },
            onClickDate: function (date,element){
                console.log(date,element)
                $('.calendar-wrapper').updateCalendarOptions({
                    date: date
                });
            },

Whenever I clicked any date, it gives this error and the date I clicked not highlighting

**Comment by wrick17** [comment]
@recepgums Not able to reproduce the issue, provided you have a proper config, it's working fine.

```
var options = {
        date: new Date().toJSON().slice(0,10).replace(/-/g,'/'),
        weekDayLength: 1,
        prevButton: 'Onceki',
        nextButton: 'Sonraki',
        monthYearSeparator: ' ',
        onClickToday: function (date) {
            alert('sd')
        },
        onClickMonthPrev: function (date) {
            return false
        },
        onClickDate: function (date,element){
            console.log(date,element)
            $('.calendar-wrapper').updateCalendarOptions({
                date: date
            });
        },
}

$('.calendar-wrapper').calendar(options);
```
