### ISSUE TITLE
disable specific weekday 

### ISSUE THREAD

**Issue by airrooms** [wrick17/calendar-plugin#17]
How to disable Sunday dates and Saturday dates every month?

**Comment by wrick17** [comment]
> How to disable Sunday dates and Saturday dates every month?
> 

Use the `disable` function 

`disable: function (date) { return false },`

Returning `false` will disable the date. Else return `true` for other days of the week.

**Comment by airrooms** [comment]
`(disable: function (date) { return true},)`

all dates become disabled. how to disable just Sunday?

**Comment by wrick17** [comment]
Get the day from the date object and return false for Sunday and true for everyone else. The function above is just for reference.

**Comment by airrooms** [comment]
how to get Sunday to form the date object? can you please help me?

**Comment by wrick17** [comment]
@RoomLea 
```
disable: function (date) { 
  const day = date.getDay(); // 0 is Sunday, 6 is Saturday
  if (day === 0 || day === 6) {
    return false;
  }
  return true;
}
```

**Comment by airrooms** [comment]
Thank you! another query about selecting weekdays, how to select Monday dates?

**Comment by wrick17** [comment]
day === 1

**Comment by airrooms** [comment]
thanks but I want to select Monday and add an event on it. which function Do I need to use for when  I click Monday Dates

**Comment by wrick17** [comment]
What kind of event? You could use the onClickDate function and check if the date is a Monday.

**Comment by airrooms** [comment]
` onClickDate:  function (date) {
            const days = date.getDay(); 
            if (days === 1){
                console.log("Monday");
                } }`

this function is not working

**Comment by wrick17** [comment]
Did you click on a Monday?

**Comment by airrooms** [comment]
Yes, but not working. nor any console error

**Comment by wrick17** [comment]
I'll have to check it. I'll let you know

**Comment by airrooms** [comment]
thank you for your help. I found the solution.

**Comment by airrooms** [comment]
![9Us8F](https://user-images.githubusercontent.com/100233858/210432426-c261c802-4d70-40bb-9981-d208f08f7ed9.jpg)
Hi, another just another query, can I achieve this results?
start form current date, week name, and month name in div, I want turn as a slider.

**Comment by wrick17** [comment]
> ![9Us8F](https://user-images.githubusercontent.com/100233858/210432426-c261c802-4d70-40bb-9981-d208f08f7ed9.jpg)
> 
> Hi, another just another query, can I achieve this results?
> 
> start form current date, week name, and month name in div, I want turn as a slider. 

Not as of now. That's way beyond the customisation capabilities of the plugin.
