### ISSUE TITLE
Dont work on mobile

### ISSUE THREAD

**Issue by StayTrue10** [wrick17/calendar-plugin#2]
![C2D5BE3D-6ABB-49FC-897D-5E39C9A45196](https://user-images.githubusercontent.com/35808948/112204617-db6a2080-8be1-11eb-879c-042c843eeffa.png)
I dont know why this is happening

**Comment by pratyushok** [comment]
Yeah there's a bug on iOS devices. A fix is in the working, should be up in a few days.

**Comment by StayTrue10** [comment]
@pratyushok thank you so much!

**Comment by pratyushok** [comment]
@StayTrue10 fix pushed. Should work fine on safari now [commit](https://github.com/wrick17/calendar-plugin/commit/de6abe1041339649756cdc2574a79747f9caf212)
