### ISSUE TITLE
Trying to use customDateHeaderProps and getting Invalid destructuring assignment target

### ISSUE THREAD

**Issue by CarlTyler** [wrick17/calendar-plugin#20]
I have the following code: 
`$('#calendar').calendar({
	  weekDayLength: 2,
	  date: MiniCalInitialDate[calDivID].format('YYYY-MM-DD'),
	  showYearDropdown: false,
	  startOnMonday: true,
	  highlightSelectedWeekday: false,
	  highlightSelectedDay: false,
	  prevButton: '',
	  nextButton: '',
	  enableMonthChange: false,
	  enableYearView: false,
	  showTodayButton: false,
	  highlightSelectedWeek: false,
    customDateHeaderProps: (05) => ({
  classes: 'highlight',
  data: {
    type: 'date-header',
    form: 'date-header-element'
  }
})
});`

the line customDateHeaderProps throws the error, I have tried the 05 in quotes and as 5 in and out of quotes.  I have also tried a javascript date.

What should be in here? I am basically trying to apply the highlight class to more than just the current week, but a range of dates.  I think this is the right option to use?

Many thanks for any help.

**Comment by CarlTyler** [comment]
I've worked out this function doesn't do what I expected it to.  It adds the custom class to every date header.  I'll use that to cycle through and check the dates, and add the necessary class.  Apologies for the question, thanks for the plugin!

**Comment by wrick17** [comment]
@CarlTyler apologies for the delayed response. Yes as you mentioned, it's just for passing props, as mentioned in the docs

`customDateHeaderProps - Function

This function can be used to pass custom classes and data attributes to the week day header elements. The week day number is passed as a parameter to the function as a Number and it should return an object with custom classes and data attributes as following`
