### ISSUE TITLE
GETTER FUNCTION - Get the currently selected date

### ISSUE THREAD

**Issue by walldiv** [wrick17/calendar-plugin#4]
I have need to get the currently selected date - outside of clicking a day to select it.  I'm trying to access the inside var "selectedDate" but am having no such luck in retrieving this variable data.

Help!

**Comment by wrick17** [comment]
For now use this piece of code. I'll try to find a better way to do this.

`const selectedDate = new Date($('.calendar-wrapper .day.selected').attr('data-date'))`

**Comment by wrick17** [comment]
@walldiv You can now use it like 👇 
```javascript
var calendar = $('#calendar-wrapper').calendar(defaultConfig);

console.log(calendar.getSelectedDate());
```
