### ISSUE TITLE
August 2021 starting with monday

### ISSUE THREAD

**Issue by Seulasslintan** [wrick17/calendar-plugin#5]
The first week of August 2021 is messed up if the week starts with Monday.
https://flic.kr/p/2mduKdw
August should start with Sunday the 1st, the second week should start with Monday the 2nd and end with Sunday the 8th. Sunday the 8th is missing.
If changed to start week with Sunday, it's fixed.
https://flic.kr/p/2mduKdw

Any short time solution for this? This is for a German website, weeks start with Monday.

**Comment by wrick17** [comment]
As of now there’s no short time solution to this.

However, I’ll probably find some time next week to resolve this. Hope you can delay it till then. I’m travelling right now, and it’ll be difficult to work on this.
