### ISSUE TITLE
Calendar Disable Click Days

### ISSUE THREAD

**Issue by johnmichaelrivera** [wrick17/calendar-plugin#6]
Hi,
Can i disable the user to click the Days?
Example: (M,T,W,T,F,S,S)
Because,upon clicking it,it changes the date to January 1970
I don't know why,but i used the calendar to get the selected date and save it to a database with appointments on that day.
Then,the problem occured upon testing it

Thanks

**Comment by pratyushok** [comment]
I see, I'll take a look and fix it as soon as possible.

**Comment by johnmichaelrivera** [comment]
Do you any have solution now?
Thanks

**Comment by wrick17** [comment]
Can you check if it's fixed now?

**Comment by johnmichaelrivera** [comment]
Hi,
Yes it is fixed now
Sorry for the late response

Thank you
