### ISSUE TITLE
Feature request: implement multi-language support

### ISSUE THREAD

**Issue by PINHOf** [wrick17/calendar-plugin#8]
Implement feature to set the values of `monthMap`, `dayMap` and `alternateDayMap`.

Nice plugin, simple and intuitive.

**Comment by pratyushok** [comment]
Can you give an example?

**Comment by PINHOf** [comment]
@pratyushok something like:

```
$('.calendar').calendar({
	...
	months: { 'january', 'february' },
	weekDays: { 'monday', 'tuesday' },
});
```
Would be nice. You can improve it as you want.

**Comment by wrick17** [comment]
@PINHOf Sure, sounds good. Let me see what I can whip up.

**Comment by wrick17** [comment]
@PINHOf added in [v1.3.0](https://github.com/wrick17/calendar-plugin/releases/tag/1.3)
