### ISSUE TITLE
Feature request: implement method to deselect date

### ISSUE THREAD

**Issue by PINHOf** [wrick17/calendar-plugin#9]
Implement method to allow the deselection of the date. Something like:

```
$('.calendar').calendar().deselectDate();
$('.calendar').calendar().deselect();
```

Real case situation: I need my user to select multiple dates (and I need to reset everytime he selects one date).

Currently, I'm using:
```
$('.calendar').find('.highlight').removeClass('highlight');
$('.calendar').find('.selected').removeClass('selected');
```

**Comment by wrick17** [comment]
That is not planned as of yet. Will take significant development and testing which I don't have much time for. If you have solved this issue, feel free to raise a PR and I'll gladly merge it.
